package net.carlevato.leapsquick;

import android.app.*; import android.appwidget.*; import android.content.*; import android.graphics.Color; import android.os.*; import android.widget.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.concurrent.*;

public class LeapsWidget extends AppWidgetProvider {
  static final String ACTION="net.carlevato.leapsquick.RECORD";
  public void onUpdate(Context c, AppWidgetManager m, int[] ids){ for(int id:ids) render(c,m,id,"Ready"); }
  public void onReceive(Context c, Intent i){ super.onReceive(c,i); if(!ACTION.equals(i.getAction())) return; PendingResult pending=goAsync(); String kind=i.getStringExtra("kind"); AppWidgetManager m=AppWidgetManager.getInstance(c); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,"Saving..."); Executors.newSingleThreadExecutor().execute(()->{ String message=record(c,kind); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,message); new Handler(Looper.getMainLooper()).postDelayed(()->refreshAll(c,"Ready"),1800); pending.finish(); }); }
  static void refreshAll(Context c,String status){ AppWidgetManager m=AppWidgetManager.getInstance(c); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,status); }
  static void render(Context c, AppWidgetManager m, int id, String status){ RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.leaps_widget); int opacity=c.getSharedPreferences("leaps",0).getInt("widgetOpacity",210); v.setInt(R.id.widget_shell,"setBackgroundColor",Color.argb(opacity,42,45,47)); v.setTextViewText(R.id.widget_status,status); v.setOnClickPendingIntent(R.id.medium,pending(c,"medium",id)); v.setOnClickPendingIntent(R.id.morning_pills,pending(c,"supplements_morning",id)); v.setOnClickPendingIntent(R.id.evening_pills,pending(c,"supplements_evening",id)); m.updateAppWidget(id,v); }
  static PendingIntent pending(Context c,String kind,int id){ Intent i=new Intent(c,LeapsWidget.class).setAction(ACTION).putExtra("kind",kind); int offset="supplements_morning".equals(kind)?10000:"supplements_evening".equals(kind)?20000:0; return PendingIntent.getBroadcast(c,id+offset,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE); }
  static String record(Context c,String kind){ try { String base=c.getSharedPreferences("leaps",0).getString("url","https://carlevato.net/leaps").replaceAll("/+$",""); HttpURLConnection h=(HttpURLConnection)new URL(base+"/api/quick-record").openConnection(); h.setRequestMethod("POST"); h.setRequestProperty("Content-Type","application/json"); h.setDoOutput(true); h.getOutputStream().write(("{\"kind\":\""+kind+"\"}").getBytes(StandardCharsets.UTF_8)); if(h.getResponseCode()>=300) return "Server error"; return "medium".equals(kind)?"Saved: Medium":"supplements_morning".equals(kind)?"Saved: D3/O3":"Saved: Magnesium"; } catch(Exception e){ return "Could not connect"; } }
}
