package net.carlevato.leapsquick;

import android.app.*; import android.appwidget.*; import android.content.*; import android.os.*; import android.widget.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.concurrent.*;

public class LeapsWidget extends AppWidgetProvider {
  static final String ACTION="net.carlevato.leapsquick.RECORD";
  public void onUpdate(Context c, AppWidgetManager m, int[] ids){ for(int id:ids) render(c,m,id,null,null); }
  public void onReceive(Context c, Intent i){ super.onReceive(c,i); if(!ACTION.equals(i.getAction())) return; PendingResult pending=goAsync(); String kind=i.getStringExtra("kind"); AppWidgetManager m=AppWidgetManager.getInstance(c); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,kind,"Saving"); Executors.newSingleThreadExecutor().execute(()->{ String message=record(c,kind); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,kind,message); new Handler(Looper.getMainLooper()).postDelayed(()->refreshAll(c,null,null),1800); pending.finish(); }); }
  static void refreshAll(Context c,String feedbackKind,String feedback){ AppWidgetManager m=AppWidgetManager.getInstance(c); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,feedbackKind,feedback); }
  static void render(Context c, AppWidgetManager m, int id, String feedbackKind,String feedback){ RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.leaps_widget); int opacity=c.getSharedPreferences("leaps",0).getInt("widgetOpacity",210); int background=opacity>=250?R.drawable.widget_action_solid:opacity>=200?R.drawable.widget_action_light:opacity>=150?R.drawable.widget_action_soft:R.drawable.widget_action_transparent; v.setInt(R.id.medium,"setBackgroundResource",background); v.setInt(R.id.morning_pills,"setBackgroundResource",background); v.setInt(R.id.evening_pills,"setBackgroundResource",background); v.setTextViewText(R.id.medium_label,"Medium"); v.setTextViewText(R.id.morning_label,"Morning"); v.setTextViewText(R.id.evening_label,"Magnesium"); if(feedbackKind!=null&&feedback!=null) v.setTextViewText("medium".equals(feedbackKind)?R.id.medium_label:"supplements_morning".equals(feedbackKind)?R.id.morning_label:R.id.evening_label,feedback); v.setOnClickPendingIntent(R.id.medium,pending(c,"medium",id)); v.setOnClickPendingIntent(R.id.morning_pills,pending(c,"supplements_morning",id)); v.setOnClickPendingIntent(R.id.evening_pills,pending(c,"supplements_evening",id)); m.updateAppWidget(id,v); }
  static PendingIntent pending(Context c,String kind,int id){ Intent i=new Intent(c,LeapsWidget.class).setAction(ACTION).putExtra("kind",kind); int offset="supplements_morning".equals(kind)?10000:"supplements_evening".equals(kind)?20000:0; return PendingIntent.getBroadcast(c,id+offset,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE); }
  static String record(Context c,String kind){ try { String base=c.getSharedPreferences("leaps",0).getString("url","https://carlevato.net/leaps").replaceAll("/+$",""); HttpURLConnection h=(HttpURLConnection)new URL(base+"/api/quick-record").openConnection(); h.setRequestMethod("POST"); h.setRequestProperty("Content-Type","application/json"); h.setDoOutput(true); h.getOutputStream().write(("{\"kind\":\""+kind+"\"}").getBytes(StandardCharsets.UTF_8)); return h.getResponseCode()<300?"Saved":"Retry"; } catch(Exception e){ return "Retry"; } }
}
