package net.carlevato.leapsquick;

import android.app.*; import android.appwidget.*; import android.content.*; import android.os.*; import android.widget.*; import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.util.concurrent.*;

public class LeapsWidget extends AppWidgetProvider {
  static final String ACTION="net.carlevato.leapsquick.RECORD";
  public void onUpdate(Context c, AppWidgetManager m, int[] ids){ for(int id:ids) render(c,m,id,null,null); }
  public void onReceive(Context c, Intent i){ super.onReceive(c,i); if(!ACTION.equals(i.getAction())) return; String kind=i.getStringExtra("kind"); if("supplements_morning".equals(kind)||"supplements_evening".equals(kind)) PillReminderReceiver.markTaken(c,kind); PendingResult pending=goAsync(); AppWidgetManager m=AppWidgetManager.getInstance(c); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,kind,"Saving"); Executors.newSingleThreadExecutor().execute(()->{ String message=record(c,kind); if("medium".equals(kind)&&"Saved".equals(message)) PillReminderReceiver.markMediumRecorded(c); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,kind,message); new Handler(Looper.getMainLooper()).postDelayed(()->refreshAll(c,null,null),1800); pending.finish(); }); }
  static void refreshAll(Context c,String feedbackKind,String feedback){ AppWidgetManager m=AppWidgetManager.getInstance(c); for(int id:m.getAppWidgetIds(new ComponentName(c,LeapsWidget.class))) render(c,m,id,feedbackKind,feedback); }
  static void render(Context c, AppWidgetManager m, int id, String feedbackKind,String feedback){ RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.leaps_widget); int opacity=c.getSharedPreferences("leaps",0).getInt("widgetOpacity",210); int background=opacity>=250?R.drawable.widget_action_solid:opacity>=200?R.drawable.widget_action_light:opacity>=150?R.drawable.widget_action_soft:R.drawable.widget_action_transparent; int[] tiles={R.id.medium,R.id.morning_pills,R.id.evening_pills,R.id.ultralearn,R.id.ams_friends,R.id.family_calls,R.id.sg_outings}; for(int tile:tiles) v.setInt(tile,"setBackgroundResource",background); setLabel(v,R.id.medium_label,"Article ✓",feedbackKind,"medium",feedback); setLabel(v,R.id.morning_label,"Morning Pills ✓",feedbackKind,"supplements_morning",feedback); setLabel(v,R.id.evening_label,"Night Pills ✓",feedbackKind,"supplements_evening",feedback); setLabel(v,R.id.ultralearn_label,"UltraLearn",feedbackKind,"ultralearn",feedback); setLabel(v,R.id.ams_friends_label,"Ams Friends",feedbackKind,"ams_friends",feedback); setLabel(v,R.id.family_label,"Family",feedbackKind,"family_calls",feedback); setLabel(v,R.id.sg_outing_label,"SG Outing",feedbackKind,"sg_outings",feedback); v.setOnClickPendingIntent(R.id.medium,pending(c,"medium",id)); v.setOnClickPendingIntent(R.id.morning_pills,pending(c,"supplements_morning",id)); v.setOnClickPendingIntent(R.id.evening_pills,pending(c,"supplements_evening",id)); v.setOnClickPendingIntent(R.id.ultralearn,pending(c,"ultralearn",id)); v.setOnClickPendingIntent(R.id.ams_friends,pending(c,"ams_friends",id)); v.setOnClickPendingIntent(R.id.family_calls,pending(c,"family_calls",id)); v.setOnClickPendingIntent(R.id.sg_outings,pending(c,"sg_outings",id)); m.updateAppWidget(id,v); }
  static void setLabel(RemoteViews v,int label,String normal,String feedbackKind,String kind,String feedback){ v.setTextViewText(label,kind.equals(feedbackKind)&&feedback!=null?feedback:normal); }
  static PendingIntent pending(Context c,String kind,int id){ Intent i=new Intent(c,LeapsWidget.class).setAction(ACTION).putExtra("kind",kind); int offset="supplements_morning".equals(kind)?10000:"supplements_evening".equals(kind)?20000:"ultralearn".equals(kind)?30000:"ams_friends".equals(kind)?40000:"family_calls".equals(kind)?50000:"sg_outings".equals(kind)?60000:0; return PendingIntent.getBroadcast(c,id+offset,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE); }
  static String record(Context c,String kind){ try { String base=c.getSharedPreferences("leaps",0).getString("url","https://carlevato.net/leaps").replaceAll("/+$",""); HttpURLConnection h=(HttpURLConnection)new URL(base+"/api/quick-record").openConnection(); h.setRequestMethod("POST"); h.setRequestProperty("Content-Type","application/json"); h.setDoOutput(true); h.getOutputStream().write(("{\"kind\":\""+kind+"\"}").getBytes(StandardCharsets.UTF_8)); return h.getResponseCode()<300?"Saved":"Retry"; } catch(Exception e){ return "Retry"; } }
}
